Task 4.2
Ususucsus/hw pull request #14
Opened 2020-03-14 16:00 UTC by Ususucsus

Решить задачу о вычислении выражения по дереву разбора из прошлого семестра. Реализовать иерархию классов, описывающих дерево разбора, используя их, реализовать класс, вычисляющий значение выражения по дереву. Классы, представляющие операнды и операторы, должны сами уметь себя вычислять и печатать.

Исходное условие:

По дереву разбора арифметического выражения вычислить его значение. Дерево разбора хранится в файле в виде (<операция> <операнд1> <операнд2>), где <операнд1> и <операнд2> сами могут быть деревьями, либо числами. Например, выражение (1 + 1) * 2 представляется в виде (* (+ 1 1) 2). Должны поддерживаться операции +, -, *, / и целые числа в качестве аргументов. Требуется построить дерево в явном виде, распечатать его (не обязательно так же, как в файле), и посчитать значение выражения обходом дерева. Может быть полезна функция ungetc (если не '(', возвращаем символ в поток и читаем число fscanf-ом). Можно считать, что входной файл корректен. Пример - по входному файлу (* (+ 1 1) 2) может печататься ( * ( + 1 1 ) 2 ) и выводиться 4.

2020-03-14 17:39 UTC, Ususucsus commented
это мем

2020-03-15 19:57 UTC, Ususucsus commented
[![codecov](https://codecov.io/gh/Ususucsus/hw/branch/master/graph/badge.svg)](https://codecov.io/gh/Ususucsus/hw)

2020-04-16 10:43 UTC, yurii-litvinov requested changes
В целом всё хорошо, но, как обычно, надо немного поправить (самое принципиальное замечание тут со свойствами LeftTreeElement и RightTreeElement у ITreeElement, но остальные тоже заодно можно поправить)

2020-04-16 10:43 UTC, yurii-litvinov commented on TreeCalculator/TreeCalculator.Test/EvaluatorTests.cs
> +        }
Методы-однострочники лучше писать через `=>`

2020-04-16 10:43 UTC, yurii-litvinov commented on TreeCalculator/TreeCalculator.Test/OperationTreeElementTests.cs
> +        }
Если тут написать нечего, то можно этот метод вообще не писать

2020-04-16 10:43 UTC, yurii-litvinov commented on TreeCalculator/TreeCalculator.Test/ValueTreeElementTests.cs
> +            Assert.AreEqual(this.treeElement.Evaluate(), 5);
Параметры наоборот, сначала expected, затем actual

2020-04-16 10:43 UTC, yurii-litvinov commented on TreeCalculator/TreeCalculator/AdditionOperationTreeElement.cs
> +    public class AdditionOperationTreeElement : OperationTreeElement, ITreeElement
OperationTreeElement и так реализует ITreeElement, можно его ещё раз тут не указывать

2020-04-16 10:43 UTC, yurii-litvinov commented on TreeCalculator/TreeCalculator/Evaluator.cs
> +                if (node == null) return;
Это лучше писать как 
```csharp
if (node == null)
{
    return;
}
```

2020-04-16 10:43 UTC, yurii-litvinov commented on TreeCalculator/TreeCalculator/Evaluator.cs
> +                for (var i = 0; i < offset; ++i) Console.Write(" ");
И это, тем более, пишется с фигурными скобками и на отдельных строках

2020-04-16 10:43 UTC, yurii-litvinov commented on TreeCalculator/TreeCalculator/Program.cs
> +            var expressionLine = file.ReadLine();
Можно File.ReadAllText("expression.txt"), меньше писать

2020-04-16 10:43 UTC, yurii-litvinov commented on TreeCalculator/TreeCalculator/ValueTreeElement.cs
> +        }
Не надо навязывать методы или свойства потомку, если потомок не может дать им содержательной реализации (это известный Code Smell). Правильнее было бы в ITreeElement не объявлять LeftTreeElement и RightTreeElement, а объявить их в OperationTreeElement

2020-05-05 18:28 UTC, yurii-litvinov approved these changes
Всё отлично, зачтена.

2020-05-05 18:29 UTC, merged