Task 2.3
Ususucsus/hw pull request #9
Opened 2020-02-24 15:38 UTC by Ususucsus

Реализовать стековый калькулятор (класс, реализующий выполнение операций +, -, *, / над арифметическим выражением в виде строки в постфиксной записи). Стек реализовать двумя способами (например, массивом или списком) в двух разных классах на основе одного интерфейса. Стековый калькулятор должен знать только про интерфейс стека.

2020-03-26 16:16 UTC, yurii-litvinov requested changes
По существу всё ок, стайлгайд над онемного поправить

2020-03-26 16:16 UTC, yurii-litvinov commented on Task23/Task23/IStack.cs
> +        public int GetLength();
Методы интерфейса и так всегда public, в этом случае модификатор доступа не пишется

2020-03-26 16:16 UTC, yurii-litvinov commented on Task23/Task23/Program.cs
> +                    case "array":
А как пользователю догадаться, что надо ввести именно array или list?

2020-03-26 16:16 UTC, yurii-litvinov commented on Task23/Task23/Program.cs
> +                var inputString = Console.ReadLine();
И тут, пользователь видит чёрную консоль и курсор, который мигает

2020-03-26 16:16 UTC, yurii-litvinov commented on Task23/Task23/Program.cs
> +                            if (int.TryParse(inputString, out var number) == false)
Не стоит сравниваться с булевыми константами. Это просто `if (!int.TryParse(inputString, out var number))`. Иначе могут подумать, что вы не понимаете булевой алгебры.

2020-03-26 16:16 UTC, yurii-litvinov commented on Task23/Task23/StackArray.cs
> +                throw new InvalidOperationException();
Не, надо сделать изменение размеров стека

2020-03-26 16:16 UTC, yurii-litvinov commented on Task23/Task23/StackArray.cs
> +            array[head++] = value;
Очень не рекомендую побочные эффекты в операторах. head++ правильнее делать на отдельной строчке, иначе его очень легко не заметить при беглом просмотре программы

2020-03-26 16:16 UTC, yurii-litvinov commented on Task23/Task23/StackCalculator.cs
> +        }
Вот такие однострочные методы, которые просто делегируют вызов, лучше делать через `=>`

2020-04-01 15:36 UTC, Ususucsus commented
Задача 3.1 тогда тут же

2020-04-16 18:16 UTC, yurii-litvinov approved these changes
Мне нравится, зачтена

2020-04-16 18:16 UTC, yurii-litvinov commented on Task23/Task23/IStack.cs
> +        int GetLength();
Я б IsEmpty и GetLength переименовал в Empty и Length и сделал read-only свойствами, так было бы симпатичнее

2020-04-16 18:16 UTC, yurii-litvinov commented on Task23/Task23/StackCalculator.cs
> +        }
Копипаст как-то

2020-04-16 18:20 UTC, merged